# Generated by Django 2.2.7 on 2019-12-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='applications',
            new_name='application',
        ),
    ]
